### ISSUE TITLE
irda in s2aio

### ISSUE THREAD

**Issue by kaszpirowskiMar** [MrYsLab/s2aio#20]
has anyone tried to set up irda (lirc) communication in s2aio? it's about pilot control ....

**Comment by MrYsLab** [comment]
I know very little about IRDA. s2aio uses modified StandardFirmata to control an Arduino and therefore needs that specific sketch to be loaded on the Arduino. My guess is that s2aio would have to be drastically modified (and probably the sketch as well) to work with IRDA.

**Comment by kaszpirowskiMar** [comment]
and if there is any other way of communication (wifi serial, bluetuth or other) ... that can handle firmataplus?

**Comment by MrYsLab** [comment]
You could use Bluetooth, or any other device that provides a com port id and can be configured to a serial baud rate of 57600. This [artticle](http://www.instructables.com/id/Wireless-Arduino-Control-Using-the-BeagleBone-Blac/) explains how to configure a Bluetooth dongle to work with an Arduino.

**Comment by kaszpirowskiMar** [comment]
in the package with firmata plus there was also firm plus wifi ..... does it also have the same properties as the company plus plus additionally wifi communication (eg service module wirles esp8664) ...?

**Comment by kaszpirowskiMar** [comment]
sorry insorry mistake ... no firmdata plus wifi only standard wifi ... question whether the functionality of wifi (espion64 module) can be added to the plus version ....?

**Comment by MrYsLab** [comment]
There may be some confusion as to what is supplied with the standard Arduino software and what sketches I supply in [FirmataPlus](https://github.com/MrYsLab/pymata-aio/raw/master/FirmataPlus/libraries.zip).

Here are the packages that are supplied with the standard Arduino software:
![with_arduino](https://user-images.githubusercontent.com/5189838/37559589-042fc9c2-29ff-11e8-98e4-5841904a1e67.png)

And here is what is in my FirmataPlus package:
![firmata_plus](https://user-images.githubusercontent.com/5189838/37559595-171e2d08-29ff-11e8-8895-169e1cd93142.png)

My sketches do not support wifi nor the esp modules. I have no plans for adding functionality to the existing sketches at this time.

**Comment by kaszpirowskiMar** [comment]
... is there any chance for firmataplus to swap the usb cable in communication on something radio? .. communication needed to control the robot from arduino on board ..... which would be controlled with scratch2.0

**Comment by MrYsLab** [comment]
I am not sure how you are defining "radio", but as explained above, you can use Bluetooth. At this time no changes are being planned because it is not clear if the Scratch folks are going to support Scratch 2.0 and its extensions once Scratch 3.0 is released later this year.

**Comment by kaszpirowskiMar** [comment]
in the plus format which is used in communication with strache20 ...? if so, I am tempted to buy the right BT module .....

**Comment by MrYsLab** [comment]
All the devices I used are listed in [this article](http://www.instructables.com/id/Wireless-Arduino-Control-Using-the-BeagleBone-Blac/). Please note that s2aio has NEVER been tested with Bluetooth, so proceed at your own risk. I may not be able to supply support if things do not work as you expect.

**Comment by kaszpirowskiMar** [comment]
ok ... I'm screwing up
