### ISSUE TITLE
le system ne peut trouver le fichier c:\program

### ISSUE THREAD

**Issue by nonoecolo** [MrYsLab/s2aio#21]
Hello !!
I have followed the installation wiki but i have this message .. Any idea ...???
![image](https://user-images.githubusercontent.com/39221795/39959770-1bae5e30-5617-11e8-956f-cdd0a637ee1a.png)

**Comment by MrYsLab** [comment]
There are a few things you can try:

1. Start s2aio with the -s  option. This will allow Scratch additional time to initialize. I would start with a large number, such as 15, and if that works you can try smaller and smaller numbers to see where it fails.

```
s2aio -s 15
```

If that doesn't work, enter:
```
s2aio -v
```
This will print the directory where the s2aio files should be installed. When I run this command, here is what I get:
![screenshot from 2018-05-12 18-17-48](https://user-images.githubusercontent.com/5189838/39962010-1fb80d10-5611-11e8-90d7-fe3605c17ca0.png)

If I then go to ScratchFiles/ScratchProjects, I see the following files:
![screenshot from 2018-05-12 18-22-54](https://user-images.githubusercontent.com/5189838/39962029-8e5dc48a-5611-11e8-87b8-c90e4fa0677c.png)

If you see a similar set of files in your directory, then you can try starting things manually by using the -c option:
```
s2aio -c no_client
```
After you see the "autodiscovery complete" message appear, start Scratch and using File/Open, select one of the files to load the blocks. For example for French blocks, you would select s2aio_base_FR.sb2.

The blocks should now be loaded.

Please let me know if any of this works for you.

**Comment by MrYsLab** [comment]
Have you had any success? If not, please let me know if you tried both suggestions above.

**Comment by MrYsLab** [comment]
Since I have not received a response, I am closing this issue. If you are still having difficulties, you can add a comment to this thread, and I will be happy to reopen the issue.
