### ISSUE TITLE
Can I make custom block in python?

### ISSUE THREAD

**Issue by oxidation99** [MrYsLab/s2aio#30]

**Comment by MrYsLab** [comment]
Unfortunately not. You can read how to create custom blocks in the [Scratch 2.0 Extension Specification.](https://en.scratch-wiki.info/w/images/ExtensionsDoc.HTTP-9-11.pdf)
You can view the coding that I did for the [English blocks](https://github.com/MrYsLab/s2aio/blob/master/s2aio/ScratchFiles/ExtensionDescriptors/s2aio.s2e), but the other supported languages are in the same directory.

The Python side is implemented as an HTTP server that routes the HTTP GET command generated by the Scratch code when a Scratch block is executed. For reporter blocks, the Python code assembles an HTTP response and sends it back to Scratch.

I am going to close this issue, but if you have any questions, you can post them here and I will see them and would be happy to answer any questions you have.
